### ISSUE TITLE
oilview

### ISSUE THREAD

**Issue by zvezdochiot** [ender672/liboil#4]
There are many functional viewers. Oilview does not carry significant functionality. Shouldn't you put it in a separate branch (gtk3)?

**Comment by ender672** [comment]
I agree -- there isn't a need for yet another image viewer. oilview is slower than feh, and has fewer features than eog. You could say the same for the entire project -- it's all been done before, and probably better.

The gtk3 viewer is just there for fun, and I've found it useful to test for performance & bugs. I don't plan on making it into anything more than a single .c file that demonstrates & visualizes the interpolator.

Maybe the only useful thing about it is that it does sRGB gamma correction, which most others don't.
